/*!
  \file constante.h
  \author Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr>
  \brief toutes les constantes necessaire au monopoly
  \date 09/01/2006
  \version 1.0
*/

#ifndef __MONOPOLY_CONSTANTES_H_
#define __MONOPOLY_CONSTANTES_H_

#define CASE_EPAISSEUR 3
#define CASE_LARGEUR 85
#define CASE_HAUTEUR 115
#define CASE_GROUPE_HAUTEUR 20

#define DETAIL_EPAISSEUR 3
#define DETAIL_LARGEUR 300
#define DETAIL_HAUTEUR 440
#define DETAIL_GROUPE_HAUTEUR 70
#define DETAIL_MESSAGE_EPAISSEUR 20
#define DETAIL_MESSAGE_POS_X POS_X_PLATEAU+CASE_HAUTEUR+(TAILLE_CENTRE-DETAIL_LARGEUR)/2-DETAIL_MESSAGE_EPAISSEUR
#define DETAIL_MESSAGE_POS_Y POS_Y_PLATEAU+CASE_HAUTEUR+(TAILLE_CENTRE-DETAIL_HAUTEUR)/2-DETAIL_MESSAGE_EPAISSEUR-100
#define DETAIL_BOUTON_POS_X DETAIL_MESSAGE_POS_X+(DETAIL_LARGEUR+2*DETAIL_MESSAGE_EPAISSEUR-165)/2
#define DETAIL_BOUTON_POS_Y DETAIL_MESSAGE_POS_Y+(DETAIL_HAUTEUR+2*DETAIL_MESSAGE_EPAISSEUR)


#define POSITION_BAS 0
#define POSITION_GAUCHE 1
#define POSITION_HAUT 2
#define POSITION_DROITE 3
#define POSITION_COIN_1 4
#define POSITION_COIN_2 5
#define POSITION_COIN_3 6
#define POSITION_COIN_4 7

#define SALLE 0
#define BUREAU_KRYSTEL 1
#define BUREAU_NADEGE 2
#define LC_WC 3
#define LC_ASCENSEUR 4
#define LC_RU 5
#define LC_PARKING 6
#define BDE 7
#define BDS 8
#define SOIREE_AREA 9
#define SOIREE_GALA 10
#define SP_APPARTEMENT 11
#define SP_BUREAU_LAURENCE 12
#define SP_MACHINE_CAFE 13
#define SP_TABLEAU 14

#define VIOLET 0
#define BLEU_CIEL 1
#define ROSE 2
#define ORANGE 3
#define ROUGE 4
#define JAUNE 5
#define VERT 6
#define BLEU 7

#define TAILLE_PLATEAU 995
#define TAILLE_CENTRE 765
#define ECRAN_LARGEUR 1280
#define ECRAN_HAUTEUR 1024
#define POS_Y_PLATEAU ((ECRAN_HAUTEUR-TAILLE_PLATEAU)/2)
#define POS_X_PLATEAU (256+POS_Y_PLATEAU)

#define ACCUEIL_LOGO_POS_Y 50
#define ACCUEIL_TITRE_POS_Y 300
#define TEXTE_POS_Y 400

#define APROPOS_HAUTEUR 350
#define APROPOS_LARGEUR 600
#define APROPOS_TEXTE_POS_X 20
#define APROPOS_TEXTE_POS_Y 20
#define APROPOS_POLICE 25

#define MULTI_HAUTEUR 130
#define MULTI_LARGEUR 600
#define MULTI_TEXTE_POS_X 20
#define MULTI_TEXTE_POS_Y 20

#define POS_X_FLECHES 500
#define POS_Y_FLECHES 500
#define LARGEUR_FLECHE 52
#define HAUTEUR_FLECHE 46

#define BTN_ACCUEIL_POS_X 500
#define BTN_ACCUEIL_POS_Y 830
#define BTN_ACCUEIL_LARGEUR 162
#define BTN_ACCUEIL_HAUTEUR 43
#define BTN_ACCUEIL_ESPACE 60

#define NOM_CHAMP_POS_X 400
#define NOM_CHAMP_POS_Y 430
#define CHAMP_POS_X 600
#define CHAMP_POS_Y 450
#define CHAMP_LARGEUR 300
#define CHAMP_HAUTEUR 30

#define PANNEAU_MENU_POS_X 10
#define PANNEAU_MENU_POS_Y 20
#define PANNEAU_MENU_LARGEUR 240
#define PANNEAU_MENU_HAUTEUR 60
#define PANNEAU_OBJET_TAILLE 40

#define PANNEAU_JOUEUR_POS_X 10
#define PANNEAU_JOUEUR_POS_Y (40+PANNEAU_MENU_HAUTEUR)
#define PANNEAU_JOUEUR_LARGEUR 240
#define PANNEAU_JOUEUR_HAUTEUR 150

#define PANNEAU_FDT_POS_X 10
#define PANNEAU_FDT_POS_Y (20+PANNEAU_JOUEUR_POS_Y+PANNEAU_JOUEUR_HAUTEUR)
#define PANNEAU_FDT_LARGEUR 240
#define PANNEAU_FDT_HAUTEUR 60

#define PANNEAU_DES_POS_X 10
#define PANNEAU_DES_POS_Y (20+PANNEAU_FDT_POS_Y+PANNEAU_FDT_HAUTEUR)
#define PANNEAU_DES_LARGEUR 240
#define PANNEAU_DES_HAUTEUR 60

#define PANNEAU_POSSESSION_POS_X 10
#define PANNEAU_POSSESSION_POS_Y (20+PANNEAU_DES_POS_Y+PANNEAU_DES_HAUTEUR)
#define PANNEAU_POSSESSION_LARGEUR 240
#define PANNEAU_POSSESSION_HAUTEUR 60

#define PROPRIETE_LARGEUR 210
#define PROPRIETE_HAUTEUR 30

#define POSITION 0
#define ARGENT 1
#define CERTIFICAT 2
#define ANNIVERSAIRE 3
#define ASTRID 4
#define CTI 5
#define CARTE_LAURENCE 6

#define PRIX_NIVEAU_MIN 500

#define DELAY 200

#define ACTION_ACHAT 0
#define ACTION_UNHYPOTHEQUE 1
#define ACTION_HYPOTHEQUE 2
#define ACTION_PLUS 3
#define ACTION_MOINS 4
#define ACTION_PLUS_MOINS 5
#define ACTION_FINIR 6
#define ACTION_PAYER 7
#define ACTION_PERDRE 8

#define ARRIVE_CASE 0
#define CLICK_CASE 1

#define MESSAGE_LARGEUR 600
#define MESSAGE_HAUTEUR 200
#define MESSAGE_MAX_LIGNE 7
#define MESSAGE_MAX_CARACTERE 64
#define MESSAGE_KRYSTEL 0
#define MESSAGE_NADEGE 1
#define MESSAGE_NORMAL 2
#define MESSAGE_QUITTER 3
#define MESSAGE_PRISON 4
#define MESSAGE_INFO_PRISON 5

#define BTN_ACHAT 0
#define BTN_UNHYPOTHEQUE 1
#define BTN_HYPOTHEQUE 2
#define BTN_PLUS 3
#define BTN_MOINS 4
#define BTN_FINIR 5

#define ERREUR -1

#define PRIX_NIVEAU_MIN 500

#define TEXTE_CENTERED -1
#define MESSAGE_CENTERED -2

#define MSG_OK 0
#define MSG_QUITTER 1
#define MSG_RUN 2
#define MSG_NULL 3
#define MSG_BACK 4
#define MSG_BTN_1 5
#define MSG_BTN_2 6
#define MSG_BTN_3 7
#define MSG_LOAD 8

#define POLICE_1 0
#define POLICE_2 1

#define MSG_INFO_TIME 2

#define PAGE_MENU 0
#define PAGE_NBRE_JOUEUR 1
#define PAGE_NOM_JOUEUR 2
#define PAGE_APROPOS 3
#define PAGE_MULTI 4

#endif
