initialisation.c
rvb_couleur init_rvb_couleur(int rouge, int vert, int bleu)
initialise une structure joueur en fonction des paramètre
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> rouge valeur pour la valeur rouge vert valeur pour la valeur vert bleu valeur pour la valeur bleu 0.0.1 la couleur
Referenced by init_tab_rvb_couleur.
void init_tab_rvb_couleur(rvb_couleur couleur[8])
initialise le tableau de couleur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> couleur tableau de couleur 0.0.1 rien
Referenced by main.
void init_case_salle(SDL_Surface *surf_ecran, rvb_couleur couleurs[8], cases *pcase, int int_type, int int_numero, int int_prix, char *str_nom1, char *str_nom2, int int_groupe, int int_prix_niveau)
initialise les cases salles
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleurs tableau de couleur pcase case en cours de création int_type le type de case int_numero numero de la case int_prix prix de la case str_nom1 nom de la case str_nom2 nom de la case int_groupe groupe de la case int_prix_niveau prix pour augmenter d'un niveau 0.0.1 rien
Referenced by init_plateau.
void init_case_association(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases associations
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_lieu_commun(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases lieu commun
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_administration(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases adimnistration
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_soiree(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases soirée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_special(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases spéciales
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_plateau(SDL_Surface *surf_ecran, rvb_couleur couleurs[8], cases **plateau)
Referenced by init_plateau_chargement, main.
joueur * init_joueur(char *nom, int numero_joueur)
initialise le joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> nom le nom du joueur numero_joueur le numéro du joueur 0.0.1 le joueur ainsi créé
Referenced by init_anneau_joueur.
void init_bureau_krystel(information *bureau_de_krystel[16])
initialise les cartes bureau de krystel
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> bureau_de_krystel tableau des cartes bureau de krystel 0.0.1 rien
Referenced by main.
void init_bureau_nadege(information *bureau_de_nadege[16])
initialise les cartes bureau de nadège
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> bureau_de_nadege tableau des cartes bureau de nadege 0.0.1 rien
Referenced by main.
possession * init_anneau_possesions()
initialise l'anneau des possesions du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> 0.0.1 NULL
Referenced by init_joueur, init_joueur_chargement.
possession * creation_possession(cases *propriete)
ajoute de façon ordonnée une propriété dans la liste
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> propriete propriété a ajouter 0.0.1 la tète de la chaine
Referenced by insertion_bonne_place_propriete.
joueur * init_anneau_joueur(int nombre_joueur, char **str_nom_joueur)
initialise le ring des joueurs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> nombre_joueur nombre de joueurs str_nom_joueur tableau du nom des joueurs 0.0.1 un des joueurs de l'anneau
Referenced by main.
cases **joueur * init_anneau_joueur_chargement(int nombre_joueur, ifstream *file, cases **plateau)
créer la liste des joueurs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> file fichier de sauvegarde plateau plateau de jeu nombre_joueur nombre de joueur 0.0.1 le premier joueur à joué
Referenced by chargement.
joueur * init_joueur_chargement(int numero_joueur, ifstream *file, cases **plateau)
créer un joueur à partir de la sauvagarde
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> file fichier de sauvegarde plateau plateau de jeu numero_joueur numéro du joueur 0.0.1 le premier joueur à joué
Referenced by init_anneau_joueur_chargement.
cases ** init_plateau_chargement(ifstream *file, cases **plateau, rvb_couleur couleurs[8], SDL_Surface *surf_ecran)
charge les données du plateau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> file fichier de sauvegarde plateau plateau de jeu couleurs tableau de couleurs surf_ecran surface de l'écran 0.0.1 le plateau
Referenced by chargement.
rvb_couleur init_rvb_couleur(int rouge, int vert, int bleu)
initialise une structure joueur en fonction des paramètre
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> rouge valeur pour la valeur rouge vert valeur pour la valeur vert bleu valeur pour la valeur bleu 0.0.1 la couleur
Referenced by init_tab_rvb_couleur.
void init_tab_rvb_couleur(rvb_couleur couleur[8])
initialise le tableau de couleur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> couleur tableau de couleur 0.0.1 rien
Referenced by main.
void init_case_salle(SDL_Surface *surf_ecran, rvb_couleur couleurs[8], cases *pcase, int int_type, int int_numero, int int_prix, char *str_nom1, char *str_nom2, int int_groupe, int int_prix_niveau)
initialise les cases salles
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleurs tableau de couleur pcase case en cours de création int_type le type de case int_numero numero de la case int_prix prix de la case str_nom1 nom de la case str_nom2 nom de la case int_groupe groupe de la case int_prix_niveau prix pour augmenter d'un niveau 0.0.1 rien
Referenced by init_plateau.
void init_case_association(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases associations
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_lieu_commun(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases lieu commun
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_administration(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases adimnistration
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_soiree(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases soirée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_case_special(SDL_Surface *surf_ecran, cases *pcase, int int_type, int int_numero)
initialise les cases spéciales
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case en cours de création int_type type de la case int_numero numéro de la case 0.0.1 rien
Referenced by init_plateau.
void init_plateau(SDL_Surface *surf_ecran, rvb_couleur couleurs[8], cases **plateau)
Referenced by init_plateau_chargement, main.
joueur * init_joueur(char *nom, int numero_joueur)
initialise le joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> nom le nom du joueur numero_joueur le numéro du joueur 0.0.1 le joueur ainsi créé
Referenced by init_anneau_joueur.
void init_bureau_krystel(information *bureau_de_krystel[16])
initialise les cartes bureau de krystel
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> bureau_de_krystel tableau des cartes bureau de krystel 0.0.1 rien
Referenced by main.
void init_bureau_nadege(information *bureau_de_nadege[16])
initialise les cartes bureau de nadège
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> bureau_de_nadege tableau des cartes bureau de nadege 0.0.1 rien
Referenced by main.
possession * init_anneau_possesions()
initialise l'anneau des possesions du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> 0.0.1 NULL
Referenced by init_joueur, init_joueur_chargement.
possession * creation_possession(cases *propriete)
ajoute de façon ordonnée une propriété dans la liste
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> propriete propriété a ajouter 0.0.1 la tète de la chaine
Referenced by insertion_bonne_place_propriete.
joueur * init_anneau_joueur(int nombre_joueur, char **str_nom_joueur)
initialise le ring des joueurs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> nombre_joueur nombre de joueurs str_nom_joueur tableau du nom des joueurs 0.0.1 un des joueurs de l'anneau
Referenced by main.
cases **joueur * init_anneau_joueur_chargement(int nombre_joueur, ifstream *file, cases **plateau)
créer la liste des joueurs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> file fichier de sauvegarde plateau plateau de jeu nombre_joueur nombre de joueur 0.0.1 le premier joueur à joué
Referenced by chargement.
joueur * init_joueur_chargement(int numero_joueur, ifstream *file, cases **plateau)
créer un joueur à partir de la sauvagarde
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> file fichier de sauvegarde plateau plateau de jeu numero_joueur numéro du joueur 0.0.1 le premier joueur à joué
Referenced by init_anneau_joueur_chargement.
cases ** init_plateau_chargement(ifstream *file, cases **plateau, rvb_couleur couleurs[8], SDL_Surface *surf_ecran)
charge les données du plateau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> file fichier de sauvegarde plateau plateau de jeu couleurs tableau de couleurs surf_ecran surface de l'écran 0.0.1 le plateau
Referenced by chargement.