interaction.h
int attente_clic(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
détermine l'action à entreprendre en fonction du clic du joueur pendant le jeu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 -1 fonctionnement normal, 0 quitter le jeu, 1 tour du joueur terminé ce qui correspond à la dernière action du joueur
Referenced by jeu.
int attente_action_accueil(SDL_Surface *surf_ecran, SDL_Surface *surf_boutons[4], SDL_Surface *surf_nombre[6], SDL_Surface *surf_fleche_gauche, SDL_Surface *surf_fleche_droite)
détermine l'action à entreprendre en fonction du clic du joueur sur la page d'accueil
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_boutons tableau des surfaces des boutons de l'accueil surf_nombre tableau des surfaces des chiffres surf_fleche_gauche surface de la flèche de gauche surf_fleche_droite surface de la flèche de droite 1.0 le nombre de joueur si ça c'est bien passé sinon -1
Referenced by affich_accueil.
int attente_action_config(SDL_Surface *surf_ecran, char **str_nom_joueur, SDL_Surface *surf_boutons[6], SDL_Surface *surf_champ, int nombre_joueur)
détermine l'action à entreprendre en fonction du clic du joueur sur la page des noms des joueurs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran str_nom_joueur tableau des noms des joueurs surf_boutons surface des 6 boutons surf_champ surfaces des champs d'écriture nombre_joueur nombre de joueurs qui jouent 1.0 action du joueur
Referenced by affich_config.
int attente_validation_propriete(SDL_Surface *surf_ecran, cases **plateau, SDL_Surface *surf_centre, cases *pcase, joueur *pj_joueur, int int_type_action)
détermine l'action à entreprendre en fonction du clic du joueur losqu'il est tombé sur une propriété
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau plateau plateau de jeu pcase case en cours de traitement pj_joueur joueur qui joue actuellement int_type_action indique le type de l'action à entreprendre 1.0 action du joueur
Referenced by attente_clic, traitement_arrive_case.
int attente_validation_message(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, char *titre, char *message, int int_type_message)
détermine l'action à entreprendre en fonction du clic du joueur lors de l'affichage d'un message
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau titre le titre du message message le message à afficher int_type_message type du message à afficher 1.0 action du joueur
Referenced by attente_clic, jeu, lancer_des, traitement_arrive_case, traitement_bureau, traitement_bureau_laurence, traitement_machine_a_cafe, traitement_soiree.
int attente_clic(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
détermine l'action à entreprendre en fonction du clic du joueur pendant le jeu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 -1 fonctionnement normal, 0 quitter le jeu, 1 tour du joueur terminé ce qui correspond à la dernière action du joueur
Referenced by jeu.
int attente_action_accueil(SDL_Surface *surf_ecran, SDL_Surface *surf_boutons[4], SDL_Surface *surf_nombre[6], SDL_Surface *surf_fleche_gauche, SDL_Surface *surf_fleche_droite)
détermine l'action à entreprendre en fonction du clic du joueur sur la page d'accueil
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_boutons tableau des surfaces des boutons de l'accueil surf_nombre tableau des surfaces des chiffres surf_fleche_gauche surface de la flèche de gauche surf_fleche_droite surface de la flèche de droite 1.0 le nombre de joueur si ça c'est bien passé sinon -1
Referenced by affich_accueil.
int attente_action_config(SDL_Surface *surf_ecran, char **str_nom_joueur, SDL_Surface *surf_boutons[6], SDL_Surface *surf_champ, int nombre_joueur)
détermine l'action à entreprendre en fonction du clic du joueur sur la page des noms des joueurs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran str_nom_joueur tableau des noms des joueurs surf_boutons surface des 6 boutons surf_champ surfaces des champs d'écriture nombre_joueur nombre de joueurs qui jouent 1.0 action du joueur
Referenced by affich_config.
int attente_validation_propriete(SDL_Surface *surf_ecran, cases **plateau, SDL_Surface *surf_centre, cases *pcase, joueur *pj_joueur, int int_type_action)
détermine l'action à entreprendre en fonction du clic du joueur losqu'il est tombé sur une propriété
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau plateau plateau de jeu pcase case en cours de traitement pj_joueur joueur qui joue actuellement int_type_action indique le type de l'action à entreprendre 1.0 action du joueur
Referenced by attente_clic, traitement_arrive_case.
int attente_validation_message(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, char *titre, char *message, int int_type_message)
détermine l'action à entreprendre en fonction du clic du joueur lors de l'affichage d'un message
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau titre le titre du message message le message à afficher int_type_message type du message à afficher 1.0 action du joueur
Referenced by attente_clic, jeu, lancer_des, traitement_arrive_case, traitement_bureau, traitement_bureau_laurence, traitement_machine_a_cafe, traitement_soiree.