outils.c
char * ajout_caractere(char *texte, int int_caractere)
ajoute un caractere (en code UTF-8) en fin de chaine
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> texte texte initial int_caractere entier correspondant à une lettre 1.0 la chaine initiale avec le caractère à la fin
Referenced by attente_action_config.
int nombre_joueur_case(joueur *pj_joueur)
calcule le nombre de joueur sur une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur le joueur actuellement en train de jouer son tour 1.0 le nombre de joueur sur la case
Referenced by aller_a_jeton, aller_en_prison_jeton, attente_validation_propriete, avancer_jeton, reculer_jeton.
void melanger_cartes(information *cartes_a_melanger[16])
mélange les cartes du bureau en effectuant une suite aléatoire d'échanges
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> cartes_a_melanger tableau des cartes à mélanger 1.0 rien
Referenced by init_bureau_krystel, init_bureau_nadege.
void swap_carte(information *cartes_a_melanger[16], int position_case1, int position_case2)
échange de cartes dans un tableau d'un bureau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> cartes_a_melanger tableau des cartes à mélanger position_case1 position de la première carte à échanger dans le tableau position_case2 position de la seconde carte à échanger dans le tableau 1.0 rien
Referenced by melanger_cartes.
void joueur_possede_tout(cases **plateau, joueur *joueur_encours)
possession* insertion_bonne_place_propriete(possession *premier_maillon, cases *case_achetee)
Referenced by init_joueur_chargement, traitement_achat.
bool possession_autres_cartes(cases **plateau, joueur *pj_joueur)
verifie si le joueur possède les autres cartes de la même couleur que celle ou il se trouve
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau tableau contenant les cases du plateau pj_joueur joueur qui joue actuellement 1.0 vrai s'il les possède sinon faux
Referenced by action_possible.
int decoupage_string(char ***str_tab, char *str_a_diviser)
divise une chaine en caractère en tableau de chaîne caractère
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> str_tab tableau de chaine de caractère pour le retour de la chaine une fois divisé str_a_diviser la chaine de caractère à diviser 1.0 le nombre de lignes
Referenced by attente_validation_message.
int action_possible(cases **plateau, int int_position_cases_etudiee, joueur *pj_joueur, int int_etat, int int_nb_tire)
analyse toutes les actions possibles pour un joueur pour une case donnée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau tableau contenant les cases du plateau int_position_cases_etudiee cases à partir de laquelle on doit faire le traitement pj_joueur joueur qui joue actuellement int_etat indique si le joueur demande a modifier le niveau d'une salle ou s'il demande une hypothèque ou s'il est seulement arriver sur une salle int_nb_tire nombre indiqué par les dés 1.0 ACTION_ACHAT s'il peut acheter, ACTION_HUNHYPOTHEQUE s'il peut déshypotéquer, ACTION_PLUS s'il peut augmenter le niveau de la salle, ACTION_MOINS s'il peut diminuer le niveau de la salle, ACTION_PLUS_MOINS s'il peut augmenter ou diminuer le niveau de la salle, ACTION_FINIR s'il ne peut que finir le tour, ACTION_PAYER s'il doit payer le loyer
Referenced by attente_clic, traitement_arrive_case.
int nombre_propriete(joueur *pj_joueur)
compte le nombre de propriétés du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement 1.0 le nombre de propriété du joueur
Referenced by affich_panneau_possessions, attente_clic.
cases * int_to_cases(int int_indice_case, joueur *pj_joueur)
à partir de l'indice de chaine des propriété elle trouve la case correspondante
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement int_indice_case indice de la case recherché fourni a partir de la liste de propriété du panneau gauche 1.0 la case voulue
Referenced by action_possible, attente_clic.
bool verification_victoire(joueur *pj_joueur)
compte le nombre de propriétés du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement 1.0 true si le joueur à gagnersinon false
Referenced by jeu.
void action_to_boutons(SDL_Surface *surf_ecran, SDL_Surface *surf_fond, int int_action, int int_etat)
définit les boutons à afficher en fonction des actions possibles sur une propriété
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_fond surface de la propriété int_action actions possibles int_etat état des boutons 1.0 nothing
Referenced by attente_validation_propriete.
void sauvegarde(cases **plateau, joueur *pj_joueur_tete)
sauvegarde de la partie
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau plateau du jeu pj_joueur_tete joueur en cours 1.0 nothing
Referenced by attente_clic, jeu.
joueur * chargement(joueur *pj_joueur, cases **plateau, rvb_couleur couleurs[8], SDL_Surface *surf_ecran)
chargement de la partie
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau plateau du jeu pj_joueur joueur en cours couleurs tableau de couleur surf_ecran surface de l'écran 1.0 un joueur de la liste de joueur
Referenced by main.
joueur *bool is_readable(const std::string &file)
test si un fichier existe
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> file le fichier à tester 1.0 si le fichier existe ou non
Referenced by attente_action_accueil.
char * ajout_caractere(char *texte, int int_caractere)
ajoute un caractere (en code UTF-8) en fin de chaine
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> texte texte initial int_caractere entier correspondant à une lettre 1.0 la chaine initiale avec le caractère à la fin
Referenced by attente_action_config.
int nombre_joueur_case(joueur *pj_joueur)
calcule le nombre de joueur sur une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur le joueur actuellement en train de jouer son tour 1.0 le nombre de joueur sur la case
Referenced by aller_a_jeton, aller_en_prison_jeton, attente_validation_propriete, avancer_jeton, reculer_jeton.
void melanger_cartes(information *cartes_a_melanger[16])
mélange les cartes du bureau en effectuant une suite aléatoire d'échanges
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> cartes_a_melanger tableau des cartes à mélanger 1.0 rien
Referenced by init_bureau_krystel, init_bureau_nadege.
void swap_carte(information *cartes_a_melanger[16], int position_case1, int position_case2)
échange de cartes dans un tableau d'un bureau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> cartes_a_melanger tableau des cartes à mélanger position_case1 position de la première carte à échanger dans le tableau position_case2 position de la seconde carte à échanger dans le tableau 1.0 rien
Referenced by melanger_cartes.
void joueur_possede_tout(cases **plateau, joueur *joueur_encours)
possession* insertion_bonne_place_propriete(possession *premier_maillon, cases *case_achetee)
Referenced by init_joueur_chargement, traitement_achat.
bool possession_autres_cartes(cases **plateau, joueur *pj_joueur)
verifie si le joueur possède les autres cartes de la même couleur que celle ou il se trouve
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau tableau contenant les cases du plateau pj_joueur joueur qui joue actuellement 1.0 vrai s'il les possède sinon faux
Referenced by action_possible.
int decoupage_string(char ***str_tab, char *str_a_diviser)
divise une chaine en caractère en tableau de chaîne caractère
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> str_tab tableau de chaine de caractère pour le retour de la chaine une fois divisé str_a_diviser la chaine de caractère à diviser 1.0 le nombre de lignes
Referenced by attente_validation_message.
int action_possible(cases **plateau, int int_position_cases_etudiee, joueur *pj_joueur, int int_etat, int int_nb_tire)
analyse toutes les actions possibles pour un joueur pour une case donnée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau tableau contenant les cases du plateau int_position_cases_etudiee cases à partir de laquelle on doit faire le traitement pj_joueur joueur qui joue actuellement int_etat indique si le joueur demande a modifier le niveau d'une salle ou s'il demande une hypothèque ou s'il est seulement arriver sur une salle int_nb_tire nombre indiqué par les dés 1.0 ACTION_ACHAT s'il peut acheter, ACTION_HUNHYPOTHEQUE s'il peut déshypotéquer, ACTION_PLUS s'il peut augmenter le niveau de la salle, ACTION_MOINS s'il peut diminuer le niveau de la salle, ACTION_PLUS_MOINS s'il peut augmenter ou diminuer le niveau de la salle, ACTION_FINIR s'il ne peut que finir le tour, ACTION_PAYER s'il doit payer le loyer
Referenced by attente_clic, traitement_arrive_case.
int nombre_propriete(joueur *pj_joueur)
compte le nombre de propriétés du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement 1.0 le nombre de propriété du joueur
Referenced by affich_panneau_possessions, attente_clic.
cases * int_to_cases(int int_indice_case, joueur *pj_joueur)
à partir de l'indice de chaine des propriété elle trouve la case correspondante
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement int_indice_case indice de la case recherché fourni a partir de la liste de propriété du panneau gauche 1.0 la case voulue
Referenced by action_possible, attente_clic.
bool verification_victoire(joueur *pj_joueur)
compte le nombre de propriétés du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement 1.0 true si le joueur à gagnersinon false
Referenced by jeu.
void action_to_boutons(SDL_Surface *surf_ecran, SDL_Surface *surf_fond, int int_action, int int_etat)
définit les boutons à afficher en fonction des actions possibles sur une propriété
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_fond surface de la propriété int_action actions possibles int_etat état des boutons 1.0 nothing
Referenced by attente_validation_propriete.
void sauvegarde(cases **plateau, joueur *pj_joueur_tete)
sauvegarde de la partie
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau plateau du jeu pj_joueur_tete joueur en cours 1.0 nothing
Referenced by attente_clic, jeu.
joueur * chargement(joueur *pj_joueur, cases **plateau, rvb_couleur couleurs[8], SDL_Surface *surf_ecran)
chargement de la partie
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> plateau plateau du jeu pj_joueur joueur en cours couleurs tableau de couleur surf_ecran surface de l'écran 1.0 un joueur de la liste de joueur
Referenced by main.
joueur *bool is_readable(const std::string &file)
test si un fichier existe
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> file le fichier à tester 1.0 si le fichier existe ou non
Referenced by attente_action_accueil.