sdl.c
void mapause(void)
SDL_Surface * rotation_90(SDL_Surface *Depart)
permet de tourner une image de 90 degré
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> Depart surface de départ 1.0 la surface tournée
Referenced by affich_case, creation_case, creation_case_bureau, creation_case_lieu_commun, creation_case_soiree.
SDL_Surface * rotation_180(SDL_Surface *Depart)
permet de tourner une image de 180 degré
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> Depart surface de départ 1.0 la surface tournée
Referenced by affich_case, creation_case, creation_case_association, creation_case_bureau, creation_case_lieu_commun.
SDL_Surface * rotation_270(SDL_Surface *Depart)
permet de tourner une image de 270 degré
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> Depart surface de départ 1.0 la surface tournée
Referenced by affich_case, creation_case, creation_case_association, creation_case_bureau, creation_case_lieu_commun.
SDL_Surface * init_sdl(void)
fonction d'initialisation de sdl
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> 1.0 la surface de l'écran
Referenced by main.
SDL_Surface * creation_joueur(int int_joueur)
créer la surface du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> int_joueur numéro du joueur 1.0 la surface du joueur
Referenced by init_joueur, init_joueur_chargement.
void affich_joueur(SDL_Surface *surf_ecran, joueur *pj_joueur, int int_position, cases *pcase)
affiche un joueur à l'écran
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur joueur en cours int_position position du joueur sur la case pcase case sur laquelle se trouve le joueur 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by affich_joueur_depart, aller_a_jeton, aller_en_prison_jeton, attente_validation_propriete, avancer_jeton, reculer_jeton.
SDL_Surface * creation_case(SDL_Surface *surf_ecran, rvb_couleur couleur, char *texte1, char *texte2, int int_prix, int int_position)
créer une case de type salle
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleur couleur du groupe texte1 première partie du nom de la case texte2 seconde partie du nom de la case int_prix prix de la case int_position coté sur lequel se trouve la case 1.0 la surface de la case
Referenced by init_case_salle.
SDL_Surface * creation_case_bureau(SDL_Surface *ecran, int int_type, int int_position)
créer une case de type bureau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de bureau int_position côté sur lequel se trouve la case 1.0 la surface de la case
Referenced by init_case_administration.
SDL_Surface * creation_case_lieu_commun(SDL_Surface *ecran, int int_type)
créer une case de type lieu commun
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de lieu commun 1.0 la surface de la case
Referenced by init_case_lieu_commun.
SDL_Surface * creation_case_association(SDL_Surface *ecran, int int_type)
créer une case de type association
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de l'association 1.0 la surface de la case
Referenced by init_case_association.
SDL_Surface * creation_case_soiree(SDL_Surface *ecran, int int_type)
créer une case de type soirée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de la soirée 1.0 la surface de la case
Referenced by init_case_soiree.
SDL_Surface * creation_case_coin(SDL_Surface *ecran, int int_type)
créer une case spécial (chacun des coins)
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de la case 1.0 la surface de la case
Referenced by init_case_special.
SDL_Surface * creation_case_detail(SDL_Surface *surf_ecran, rvb_couleur couleur, char *texte, int int_prix, int int_prix_niveau)
créer la surface de la case détaillé
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleur couleur du groupe de la case texte nom de la case int_prix prix de la case int_prix_niveau prix d'un niveau de la case 1.0 la surface de la case détaillé
Referenced by init_case_salle.
SDL_Surface * creation_case_detail_lc(SDL_Surface *surf_ecran, int int_type)
créer la surface de la case détaille d'une case lieu commun
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_type type de lieu commun 1.0 la surface de la case détaillé
Referenced by init_case_lieu_commun.
creation_case_detail_assoc(SDL_Surface *surf_ecran, int int_type)
créer la surface de la case détaille d'une case association
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_type type d'association 1.0 la surface de la case détaillé
Referenced by init_case_association.
SDL_Surface * creation_case_propriete(SDL_Surface *surf_ecran, rvb_couleur couleur, char *texte)
créer la surface de la propriété qui s'affichera dans le panneau des propriétés
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleur couleur du groupe de la case texte nom de la case 1.0 la surface la propriété
Referenced by init_case_association, init_case_lieu_commun, init_case_salle.
int affich_accueil(SDL_Surface *surf_ecran)
affiche la page d'accueil
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran 1.0 une action demandée du joueur
Referenced by main.
int affich_config(SDL_Surface *surf_ecran, char **str_nom_joueur, int nombre_joueur)
affiche la page de configuration de la partie
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran str_nom_joueur tableau des noms des joueurs nombre_joueur nombre de joueur dans la partie 1.0 une action demandée du joueur
Referenced by main.
void affich_case(SDL_Surface *surf_ecran, cases *pcase)
affiche une case à l'écran
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case à afficher 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by aller_a_jeton, aller_en_prison_jeton, attente_validation_propriete, avancer_jeton, jeu, reculer_jeton.
void affich_case_detail(SDL_Surface *surf_ecran, cases *pcase)
affiche le détail d'une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case dont on doti afficher le détail 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
void affich_centre(SDL_Surface *surf_ecran, SDL_Surface *surf_centre)
affiche le centre du plateau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface du centre 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_validation_message, attente_validation_propriete, jeu.
void affich_panneau_menu(SDL_Surface *surf_ecran, int int_etat_bouton)
affiche le panneau du menu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_etat_bouton état des boutons 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_panneau_joueur(SDL_Surface *surf_ecran, joueur *j_anneau_joueurs)
affiche le panneau d'information sur le joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran j_anneau_joueurs joueur en cours 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_panneau_possessions(SDL_Surface *surf_ecran, joueur *j_anneau_joueurs)
affiche le panneau des possessions du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran j_anneau_joueurs joueur en cours 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_possessions_cache(SDL_Surface *surf_ecran)
affiche le cache du panneau de possesion du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by jeu.
void affich_panneau_des_bouton(SDL_Surface *surf_ecran, int int_image)
affiche le panneau contenant le bouton lancer dé
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_image score du dé 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
SDL_Surface ** creation_des(void)
renvoit un tableau de surface contenant chacune des faces du dé
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> 1.0 le tableau des surfaces des faces du dé
Referenced by lancer_des.
void destruction_des(SDL_Surface **surf_des)
détruit les surfaces des dés
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_des tableau des surfaces des faces d'un dé 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by lancer_des.
void affich_panneau_fdt(SDL_Surface *surf_ecran, bool bool_etat)
affiche le panneau du menu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran bool_etat état des boutons 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_panneau_des(SDL_Surface *surf_ecran, SDL_Surface **surf_des, int int_de1, int int_de2)
affiche le panneau du menu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_des tableau des surfaces des face du dé int_de1 score du dé numéro 1 int_de2 score du dé numéro 2 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by lancer_des.
void affich_joueur_depart(SDL_Surface *surf_ecran, cases **plateau, joueur *j_anneau_joueurs, int nombre_joueur)
affiche tout les joueurs sur la case de départ
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran plateau plateau de jeu j_anneau_joueurs liste chaînée des joueurs nombre_joueur nombre de joueur 1.0 action ud joueur
Referenced by jeu.
int affich_validation_propriete(SDL_Surface *surf_ecran, SDL_Surface *surf_fond, int int_etat, int int_nombre_boutons,...)
affiche le message des propriété ainsi que les boutons d'actions possibles
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_fond surface de la propriété int_etat état des boutons int_nombre_boutons nombre de boutons à afficher ... liste des boutons à afficher 1.0 un entier d'état
Referenced by action_to_boutons.
SDL_Surface * creation_message(SDL_Surface *surf_ecran, char *titre, char **message, int int_type_message, int int_nbre_ligne)
créer la surface d'un message à afficher
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran titre titre du message message message à afficher int_type_message type du message à afficher int_nbre_ligne nombre de ligne du message 1.0 la surface du message
Referenced by attente_validation_message.
void affich_message(SDL_Surface *surf_ecran, SDL_Surface *surf_message, int int_type_message, int int_etat)
affiche un message à l'écran
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_message surface du message int_type_message type du message à afficher int_etat état des boutons 1.0 rien
Referenced by attente_validation_message.
void mapause(void)
SDL_Surface * rotation_90(SDL_Surface *Depart)
permet de tourner une image de 90 degré
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> Depart surface de départ 1.0 la surface tournée
Referenced by affich_case, creation_case, creation_case_bureau, creation_case_lieu_commun, creation_case_soiree.
SDL_Surface * rotation_180(SDL_Surface *Depart)
permet de tourner une image de 180 degré
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> Depart surface de départ 1.0 la surface tournée
Referenced by affich_case, creation_case, creation_case_association, creation_case_bureau, creation_case_lieu_commun.
SDL_Surface * rotation_270(SDL_Surface *Depart)
permet de tourner une image de 270 degré
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> Depart surface de départ 1.0 la surface tournée
Referenced by affich_case, creation_case, creation_case_association, creation_case_bureau, creation_case_lieu_commun.
SDL_Surface * init_sdl(void)
fonction d'initialisation de sdl
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> 1.0 la surface de l'écran
Referenced by main.
SDL_Surface * creation_joueur(int int_joueur)
créer la surface du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> int_joueur numéro du joueur 1.0 la surface du joueur
Referenced by init_joueur, init_joueur_chargement.
void affich_joueur(SDL_Surface *surf_ecran, joueur *pj_joueur, int int_position, cases *pcase)
affiche un joueur à l'écran
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur joueur en cours int_position position du joueur sur la case pcase case sur laquelle se trouve le joueur 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by affich_joueur_depart, aller_a_jeton, aller_en_prison_jeton, attente_validation_propriete, avancer_jeton, reculer_jeton.
SDL_Surface * creation_case(SDL_Surface *surf_ecran, rvb_couleur couleur, char *texte1, char *texte2, int int_prix, int int_position)
créer une case de type salle
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleur couleur du groupe texte1 première partie du nom de la case texte2 seconde partie du nom de la case int_prix prix de la case int_position coté sur lequel se trouve la case 1.0 la surface de la case
Referenced by init_case_salle.
SDL_Surface * creation_case_bureau(SDL_Surface *ecran, int int_type, int int_position)
créer une case de type bureau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de bureau int_position côté sur lequel se trouve la case 1.0 la surface de la case
Referenced by init_case_administration.
SDL_Surface * creation_case_lieu_commun(SDL_Surface *ecran, int int_type)
créer une case de type lieu commun
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de lieu commun 1.0 la surface de la case
Referenced by init_case_lieu_commun.
SDL_Surface * creation_case_association(SDL_Surface *ecran, int int_type)
créer une case de type association
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de l'association 1.0 la surface de la case
Referenced by init_case_association.
SDL_Surface * creation_case_soiree(SDL_Surface *ecran, int int_type)
créer une case de type soirée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de la soirée 1.0 la surface de la case
Referenced by init_case_soiree.
SDL_Surface * creation_case_coin(SDL_Surface *ecran, int int_type)
créer une case spécial (chacun des coins)
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> ecran surface de l'écran int_type type de la case 1.0 la surface de la case
Referenced by init_case_special.
SDL_Surface * creation_case_detail(SDL_Surface *surf_ecran, rvb_couleur couleur, char *texte, int int_prix, int int_prix_niveau)
créer la surface de la case détaillé
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleur couleur du groupe de la case texte nom de la case int_prix prix de la case int_prix_niveau prix d'un niveau de la case 1.0 la surface de la case détaillé
Referenced by init_case_salle.
SDL_Surface * creation_case_detail_lc(SDL_Surface *surf_ecran, int int_type)
créer la surface de la case détaille d'une case lieu commun
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_type type de lieu commun 1.0 la surface de la case détaillé
Referenced by init_case_lieu_commun.
creation_case_detail_assoc(SDL_Surface *surf_ecran, int int_type)
créer la surface de la case détaille d'une case association
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_type type d'association 1.0 la surface de la case détaillé
Referenced by init_case_association.
SDL_Surface * creation_case_propriete(SDL_Surface *surf_ecran, rvb_couleur couleur, char *texte)
créer la surface de la propriété qui s'affichera dans le panneau des propriétés
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran couleur couleur du groupe de la case texte nom de la case 1.0 la surface la propriété
Referenced by init_case_association, init_case_lieu_commun, init_case_salle.
int affich_accueil(SDL_Surface *surf_ecran)
affiche la page d'accueil
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran 1.0 une action demandée du joueur
Referenced by main.
int affich_config(SDL_Surface *surf_ecran, char **str_nom_joueur, int nombre_joueur)
affiche la page de configuration de la partie
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran str_nom_joueur tableau des noms des joueurs nombre_joueur nombre de joueur dans la partie 1.0 une action demandée du joueur
Referenced by main.
void affich_case(SDL_Surface *surf_ecran, cases *pcase)
affiche une case à l'écran
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case à afficher 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by aller_a_jeton, aller_en_prison_jeton, attente_validation_propriete, avancer_jeton, jeu, reculer_jeton.
void affich_case_detail(SDL_Surface *surf_ecran, cases *pcase)
affiche le détail d'une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran pcase case dont on doti afficher le détail 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
void affich_centre(SDL_Surface *surf_ecran, SDL_Surface *surf_centre)
affiche le centre du plateau
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface du centre 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_validation_message, attente_validation_propriete, jeu.
void affich_panneau_menu(SDL_Surface *surf_ecran, int int_etat_bouton)
affiche le panneau du menu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_etat_bouton état des boutons 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_panneau_joueur(SDL_Surface *surf_ecran, joueur *j_anneau_joueurs)
affiche le panneau d'information sur le joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran j_anneau_joueurs joueur en cours 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_panneau_possessions(SDL_Surface *surf_ecran, joueur *j_anneau_joueurs)
affiche le panneau des possessions du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran j_anneau_joueurs joueur en cours 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_possessions_cache(SDL_Surface *surf_ecran)
affiche le cache du panneau de possesion du joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by jeu.
void affich_panneau_des_bouton(SDL_Surface *surf_ecran, int int_image)
affiche le panneau contenant le bouton lancer dé
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran int_image score du dé 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
SDL_Surface ** creation_des(void)
renvoit un tableau de surface contenant chacune des faces du dé
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> 1.0 le tableau des surfaces des faces du dé
Referenced by lancer_des.
void destruction_des(SDL_Surface **surf_des)
détruit les surfaces des dés
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_des tableau des surfaces des faces d'un dé 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by lancer_des.
void affich_panneau_fdt(SDL_Surface *surf_ecran, bool bool_etat)
affiche le panneau du menu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran bool_etat état des boutons 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by attente_clic, jeu.
void affich_panneau_des(SDL_Surface *surf_ecran, SDL_Surface **surf_des, int int_de1, int int_de2)
affiche le panneau du menu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_des tableau des surfaces des face du dé int_de1 score du dé numéro 1 int_de2 score du dé numéro 2 1.0 +++++++++++++++++++++++++++++++++++++++++++++++++
Referenced by lancer_des.
void affich_joueur_depart(SDL_Surface *surf_ecran, cases **plateau, joueur *j_anneau_joueurs, int nombre_joueur)
affiche tout les joueurs sur la case de départ
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran plateau plateau de jeu j_anneau_joueurs liste chaînée des joueurs nombre_joueur nombre de joueur 1.0 action ud joueur
Referenced by jeu.
int affich_validation_propriete(SDL_Surface *surf_ecran, SDL_Surface *surf_fond, int int_etat, int int_nombre_boutons,...)
affiche le message des propriété ainsi que les boutons d'actions possibles
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_fond surface de la propriété int_etat état des boutons int_nombre_boutons nombre de boutons à afficher ... liste des boutons à afficher 1.0 un entier d'état
Referenced by action_to_boutons.
SDL_Surface * creation_message(SDL_Surface *surf_ecran, char *titre, char **message, int int_type_message, int int_nbre_ligne)
créer la surface d'un message à afficher
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran titre titre du message message message à afficher int_type_message type du message à afficher int_nbre_ligne nombre de ligne du message 1.0 la surface du message
Referenced by attente_validation_message.
void affich_message(SDL_Surface *surf_ecran, SDL_Surface *surf_message, int int_type_message, int int_etat)
affiche un message à l'écran
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_message surface du message int_type_message type du message à afficher int_etat état des boutons 1.0 rien
Referenced by attente_validation_message.