traitement.c
void jeu(SDL_Surface *surf_ecran, joueur *pj_joueur_encours, cases **plateau, int nombre_joueur, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
initialise le jeu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur_encours joueur qui joue actuellement plateau tableau contenant les cases du plateau nombre_joueur nombre de joueurs qui jouent bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by main.
int lancer_des(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau)
fonction chargée de simuler le lancement des dés
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 le nombre obtenue par les dés
Referenced by attente_clic, traitement_bureau_laurence.
void reculer_jeton(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
recule le joueur de 3 cases
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by traitement_bureau.
void avancer_jeton(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, int int_nb_tire, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
avance le jeton case par case, traite le passage par la case départ
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau int_nb_tire nombre obtenu lors du lancer des dés pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by attente_clic, traitement_bureau_laurence.
void aller_a_jeton(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, int int_position_voulue, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16], int delai)
avance le jeton case par case, traite le passage par la case départ
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface du centre du plateau int_position_voulue position voulue pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège delai délai du déplacement entre deux cases 1.0 rien
Referenced by traitement_bureau.
void aller_en_prison_jeton(SDL_Surface *surf_ecran, joueur *pj_joueur, cases **plateau)
envoi le joueur directement en prison
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 rien
Referenced by lancer_des, traitement_arrive_case, traitement_bureau.
bool traitement_achat(cases *case_achetee, joueur *joueur_actuel)
traitement l'achat d'une propriété
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> case_achetee indice des la case achetée joueur_actuel l'acheteur 1.0 booléen qui indique si la fonction s'est bbien déroulée
Referenced by attente_validation_propriete, joueur_possede_tout.
void traitement_case_depart(SDL_Surface *surf_ecran, joueur *pj_joueur)
ajoute l'argent au joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur joueur qui joue actuellement 1.0 rien
Referenced by aller_a_jeton, avancer_jeton.
bool traitement_payer_loyer(joueur *joueur_qui_paye, joueur *joueur_paye, int int_montant)
paye les loyer d'une salle
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_qui_paye joueur à qui on prend les sous joueur_paye joueur à qui on donne les sous int_montant montant de la transaction 1.0 booléen indiquant si la fonction c'est bien dérouler
Referenced by traitement_arrive_case.
bool traitement_mise_en_hypotheque(joueur *joueur_actuel, cases *case_hypothequee)
met en place une hypothèque
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_actuel joueur qui joue actuellement case_hypothequee indice de la case à hypothéquer 1.0 booléen indiquant si la fonction c'est bien dérouler
int traitement_loyer_association(joueur *joueur_paye, int int_nb_tire)
calcul le loyer d'une association
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_paye joueur à qui on doit les sous int_nb_tire nombre indiqué par le dés 1.0 le loyer à payer
Referenced by action_possible, traitement_arrive_case.
int traitement_loyer_lieu_commun(joueur *pj_joueur)
calcul le loyer pour les lieux communs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> pj_joueur joueur à qui on doit les sous 1.0 le montant du loyer
Referenced by action_possible, traitement_arrive_case.
bool traitement_rachat_hypotheque(joueur *joueur_actuel, cases *case_hypothequee)
rachète une hypothèque
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_actuel joueur qui joue actuellement case_hypothequee indice de la case à déshypothéquer 1.0 booléen indiquant si la fonction c'est bien dérouler
bool traitement_augmentation_niveau(cases *pcase, joueur *pj_joueur)
augmente le niveau d'une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement pcase case dont on doit changer le niveau 1.0 booléen indiquant si la fonction s'est bien déroulée
Referenced by attente_validation_propriete.
void traitement_diminution_niveau(cases *pcase, joueur *pj_joueur)
diminue le niveau d'une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement pcase case dont on doit changer le niveau 1.0 booléen indiquant si la fonction s'est bien déroulée
Referenced by attente_validation_propriete.
void traitement_arrive_case(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur, information *bureau_de_krystel[16], information *bureau_de_nadege[16], int int_nombre_tire)
effectue les action necessaire lors de l'arrivée sur une case en fonction de son type
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement int_nombre_tire nombre obtenu lors du lancer des dés plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by aller_a_jeton, avancer_jeton, reculer_jeton.
void traitement_soiree(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau)
fait payer le joueur suivant la case soirée sur laquelle il est
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 rien
Referenced by traitement_arrive_case.
void traitement_machine_a_cafe(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur)
donne au joueur l'argent de la machine à café
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 rien
Referenced by traitement_arrive_case.
void traitement_bureau_laurence(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
effectue les traitement necessaire lorsqu'un joueur est dans le bureau de laurence
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège rien
Referenced by attente_clic, traitement_arrive_case.
void traitement_bureau(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur, information *le_bureau[16], information *bureau_de_krystel[16], information *bureau_de_nadege[16], int int_id_bureau)
tire une carte du bureau voulue et effectue le traitement en fonction de la carte tirée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau le_bureau tableau des cartes bureau à utiliser bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège int_id_bureau id du bureau à utiliser 1.0 rien
Referenced by traitement_arrive_case, traitement_bureau.
void traitement_elimination_joueur(joueur *joueur_eliminer)
libère les propriété et l'espace mémoire du joueur et de ses possessions
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_eliminer le joueur à éliminer 1.0 rien
Referenced by traitement_perdu.
void traitement_perdu(joueur *pj_joueur)
Referenced by traitement_bureau.
void jeu(SDL_Surface *surf_ecran, joueur *pj_joueur_encours, cases **plateau, int nombre_joueur, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
initialise le jeu
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur_encours joueur qui joue actuellement plateau tableau contenant les cases du plateau nombre_joueur nombre de joueurs qui jouent bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by main.
int lancer_des(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau)
fonction chargée de simuler le lancement des dés
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 le nombre obtenue par les dés
Referenced by attente_clic, traitement_bureau_laurence.
void reculer_jeton(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
recule le joueur de 3 cases
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by traitement_bureau.
void avancer_jeton(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, int int_nb_tire, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
avance le jeton case par case, traite le passage par la case départ
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau int_nb_tire nombre obtenu lors du lancer des dés pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by attente_clic, traitement_bureau_laurence.
void aller_a_jeton(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, int int_position_voulue, joueur *pj_joueur, cases **plateau, information *bureau_de_krystel[16], information *bureau_de_nadege[16], int delai)
avance le jeton case par case, traite le passage par la case départ
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface du centre du plateau int_position_voulue position voulue pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège delai délai du déplacement entre deux cases 1.0 rien
Referenced by traitement_bureau.
void aller_en_prison_jeton(SDL_Surface *surf_ecran, joueur *pj_joueur, cases **plateau)
envoi le joueur directement en prison
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 rien
Referenced by lancer_des, traitement_arrive_case, traitement_bureau.
bool traitement_achat(cases *case_achetee, joueur *joueur_actuel)
traitement l'achat d'une propriété
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> case_achetee indice des la case achetée joueur_actuel l'acheteur 1.0 booléen qui indique si la fonction s'est bbien déroulée
Referenced by attente_validation_propriete, joueur_possede_tout.
void traitement_case_depart(SDL_Surface *surf_ecran, joueur *pj_joueur)
ajoute l'argent au joueur
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran pj_joueur joueur qui joue actuellement 1.0 rien
Referenced by aller_a_jeton, avancer_jeton.
bool traitement_payer_loyer(joueur *joueur_qui_paye, joueur *joueur_paye, int int_montant)
paye les loyer d'une salle
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_qui_paye joueur à qui on prend les sous joueur_paye joueur à qui on donne les sous int_montant montant de la transaction 1.0 booléen indiquant si la fonction c'est bien dérouler
Referenced by traitement_arrive_case.
bool traitement_mise_en_hypotheque(joueur *joueur_actuel, cases *case_hypothequee)
met en place une hypothèque
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_actuel joueur qui joue actuellement case_hypothequee indice de la case à hypothéquer 1.0 booléen indiquant si la fonction c'est bien dérouler
int traitement_loyer_association(joueur *joueur_paye, int int_nb_tire)
calcul le loyer d'une association
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_paye joueur à qui on doit les sous int_nb_tire nombre indiqué par le dés 1.0 le loyer à payer
Referenced by action_possible, traitement_arrive_case.
int traitement_loyer_lieu_commun(joueur *pj_joueur)
calcul le loyer pour les lieux communs
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> pj_joueur joueur à qui on doit les sous 1.0 le montant du loyer
Referenced by action_possible, traitement_arrive_case.
bool traitement_rachat_hypotheque(joueur *joueur_actuel, cases *case_hypothequee)
rachète une hypothèque
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_actuel joueur qui joue actuellement case_hypothequee indice de la case à déshypothéquer 1.0 booléen indiquant si la fonction c'est bien dérouler
bool traitement_augmentation_niveau(cases *pcase, joueur *pj_joueur)
augmente le niveau d'une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement pcase case dont on doit changer le niveau 1.0 booléen indiquant si la fonction s'est bien déroulée
Referenced by attente_validation_propriete.
void traitement_diminution_niveau(cases *pcase, joueur *pj_joueur)
diminue le niveau d'une case
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> pj_joueur joueur qui joue actuellement pcase case dont on doit changer le niveau 1.0 booléen indiquant si la fonction s'est bien déroulée
Referenced by attente_validation_propriete.
void traitement_arrive_case(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur, information *bureau_de_krystel[16], information *bureau_de_nadege[16], int int_nombre_tire)
effectue les action necessaire lors de l'arrivée sur une case en fonction de son type
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement int_nombre_tire nombre obtenu lors du lancer des dés plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège 1.0 rien
Referenced by aller_a_jeton, avancer_jeton, reculer_jeton.
void traitement_soiree(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, joueur *pj_joueur, cases **plateau)
fait payer le joueur suivant la case soirée sur laquelle il est
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 rien
Referenced by traitement_arrive_case.
void traitement_machine_a_cafe(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur)
donne au joueur l'argent de la machine à café
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau 1.0 rien
Referenced by traitement_arrive_case.
void traitement_bureau_laurence(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur, information *bureau_de_krystel[16], information *bureau_de_nadege[16])
effectue les traitement necessaire lorsqu'un joueur est dans le bureau de laurence
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège rien
Referenced by attente_clic, traitement_arrive_case.
void traitement_bureau(SDL_Surface *surf_ecran, SDL_Surface *surf_centre, cases **plateau, joueur *pj_joueur, information *le_bureau[16], information *bureau_de_krystel[16], information *bureau_de_nadege[16], int int_id_bureau)
tire une carte du bureau voulue et effectue le traitement en fonction de la carte tirée
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> surf_ecran surface de l'écran surf_centre surface centrale du plateau pj_joueur joueur qui joue actuellement plateau tableau contenant les cases du plateau le_bureau tableau des cartes bureau à utiliser bureau_de_krystel tableau des cartes bureau de krystel bureau_de_nadege tableau des cartes bureau de nadège int_id_bureau id du bureau à utiliser 1.0 rien
Referenced by traitement_arrive_case, traitement_bureau.
void traitement_elimination_joueur(joueur *joueur_eliminer)
libère les propriété et l'espace mémoire du joueur et de ses possessions
Franck Trey <franck.trey@eisti.fr>, Florian Lefevre <Florian.lefevre@eisti.fr> joueur_eliminer le joueur à éliminer 1.0 rien
Referenced by traitement_perdu.
void traitement_perdu(joueur *pj_joueur)
Referenced by traitement_bureau.